name: Deploy master branch in DO Container Registry
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  Build-and-push-DockerCont:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login in Container Registry Digital Ocean
        run: doctl registry login

      - name: Build Docker Container
        run: docker build ./ -tag ${{ secrets.DOREGISTRY}}/feecc-cameraman:master
      
      - name: Tag container for Container Registry Digital Ocean
        run: docker tag ${{ secrets.DOREGISTRY}}/feecc-cameraman:master ${{ secrets.DOREGISTRY}}/feecc-cameraman

      - name: Push container in Container Registry Digital Ocean
        run: docker push ${{ secrets.DOREGISTRY}}/feecc-cameraman:master